workspace:
  base: /go
  path: src/github.com/udistrital/${DRONE_REPO##udistrital/}
  when:
      branch: [master, test]
      event: [push, pull_request]
      
pipeline:

  # build and test the go program
  nodejs:
    image: node:12.6.0
    commands:
     - npm i
     - npm run build:test
    when:
      branch: [test]
      event: [push, pull_request]
      
  
