
export let FORM_MENU_OPCION = {
    titulo: 'MenuOpcion',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'MenuOpcion',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Id',
        label_i18n: 'id',
        placeholder_i18n: 'id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Nombre',
        label_i18n: 'nombre',
        placeholder_i18n: 'nombre',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Descripcion',
        label_i18n: 'descripcion',
        placeholder_i18n: 'descripcion',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Url',
        label_i18n: 'url',
        placeholder_i18n: 'url',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Layout',
        label_i18n: 'layout',
        placeholder_i18n: 'layout',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'selectmultiple',
        claseGrid: 'col-6',
        nombre: 'Aplicacion',
        label_i18n: 'aplicacion',
        placeholder_i18n: 'aplicacion',
        requerido: true,
        tipo: 'Aplicacion',
        // key: 'Name',
        opciones: [],
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'TipoOpcion',
        label_i18n: 'tipo_opcion',
        placeholder_i18n: 'tipo_opcion',
        requerido: true,
        tipo: 'text',
    },
    ],
}
